### ISSUE TITLE
Cant find the jar in s3 bucket 

### ISSUE THREAD

**Issue by georgethms10** [JacobASeverson/s3-maven-repo-example#1]
Hi I followed through the tutorial and ran ./gradlew publish from STS but i cant find my jar in my s3 bucket. 

1. I avoided creating an s3 bucket since i already had one 
1. I avoided setting policy since the policy was already set to {block all public access} [should i change to some else the code in the gradle file i dont understand to update policy]

how can i check whether the connection between s3 bucket was successful.

**Comment by JacobASeverson** [comment]
Hi @georgethms10, It's been years since I've run this but I can help when time permits. Is there any helpful output when run with debug logging?

**Comment by JacobASeverson** [comment]
Closing. If still an issue please provide more info.
